######
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: poc-nodejs-ing
  namespace: my-namespace
  labels:
    app: poc-nodejs
    topic: my-namespace
    language: nodejs
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - ${HOST}
    secretName: nodejs-api-tls
  rules:
  - host: ${HOST}
    http:
      paths:
      - path: /nodejs-api
        backend:
          serviceName: poc-nodejs
          servicePort: api-svc