######
apiVersion: v1
kind: Service
metadata:
  name: poc-nodejs
  namespace: my-namespace
  labels:
    app: poc-nodejs
    topic: my-namespace
    language: nodejs
spec:
  ports:
  - name: api-svc
    port: ${APP_PORT}
    targetPort: api-pod
    protocol: TCP
  selector:
    app: poc-nodejs
    topic: my-namespace
    language: nodejs